sudo: required

language: python

python:
  - "3.6"

services:
  - docker

install:
  - docker pull fedora
  - docker build -t tasker:tasker .

before_install:
  - docker pull redis
  - docker pull mongo
  - |
    docker run \
      --interactive \
      --tty \
      --detach \
      --publish=6379:6379 \
      redis bash -c " \
        redis-server \
          --save '' \
          --protected-mode no \
          --bind 0.0.0.0 \
          --requirepass e082ebf6c7fff3997c4bb1cb64d6bdecd0351fa270402d98d35acceef07c6b97 \
      "
  - |
    docker run \
      --interactive \
      --tty \
      --detach \
      --publish=6380:6379 \
      redis bash -c " \
        redis-server \
          --save '' \
          --protected-mode no \
          --bind 0.0.0.0 \
          --requirepass e082ebf6c7fff3997c4bb1cb64d6bdecd0351fa270402d98d35acceef07c6b97 \
      "
  - |
    docker run \
      --interactive \
      --tty \
      --detach \
      --publish=27030:27017 \
      mongo
  - |
    docker run \
      --interactive \
      --tty \
      --detach \
      --publish=50001:50001 \
      --volume "${PWD}":/tasker \
      tasker:tasker bash -c " \
        cd /tasker; \
        python3.6 -m tasker.server.server; \
      "

script:
  - |
    docker run \
      --interactive \
      --tty \
      --rm \
      --net=host \
      --volume "${PWD}":/tasker \
      tasker:tasker bash -c " \
        cd /tasker; \
        pytest tasker/tests; \
      "
