# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasker.proto',
  package='tasker_server',
  syntax='proto3',
  serialized_pb=_b('\n\x0ctasker.proto\x12\rtasker_server\"+\n\rKeySetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"9\n\x0eKeySetResponse\x12\x13\n\x0bkey_was_set\x18\x01 \x01(\x08\x12\x12\n\nkey_is_new\x18\x02 \x01(\x08\"\x1c\n\rKeyGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"3\n\x0eKeyGetResponse\x12\x12\n\nkey_exists\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1f\n\x10KeyDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"$\n\x11KeyDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\">\n\x0fQueuePopRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12\x17\n\x0fnumber_of_items\x18\x02 \x01(\x05\"!\n\x10QueuePopResponse\x12\r\n\x05items\x18\x01 \x03(\x0c\"G\n\x10QueuePushRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\t\x12\r\n\x05items\x18\x03 \x03(\x0c\"$\n\x11QueuePushResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x12QueueDeleteRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\"&\n\x13QueueDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x12QueueLengthRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\"+\n\x13QueueLengthResponse\x12\x14\n\x0cqueue_length\x18\x01 \x01(\x05\x32\xca\x04\n\x0cTaskerServer\x12H\n\x07key_set\x12\x1c.tasker_server.KeySetRequest\x1a\x1d.tasker_server.KeySetResponse\"\x00\x12H\n\x07key_get\x12\x1c.tasker_server.KeyGetRequest\x1a\x1d.tasker_server.KeyGetResponse\"\x00\x12Q\n\nkey_delete\x12\x1f.tasker_server.KeyDeleteRequest\x1a .tasker_server.KeyDeleteResponse\"\x00\x12N\n\tqueue_pop\x12\x1e.tasker_server.QueuePopRequest\x1a\x1f.tasker_server.QueuePopResponse\"\x00\x12Q\n\nqueue_push\x12\x1f.tasker_server.QueuePushRequest\x1a .tasker_server.QueuePushResponse\"\x00\x12W\n\x0cqueue_delete\x12!.tasker_server.QueueDeleteRequest\x1a\".tasker_server.QueueDeleteResponse\"\x00\x12W\n\x0cqueue_length\x12!.tasker_server.QueueLengthRequest\x1a\".tasker_server.QueueLengthResponse\"\x00\x62\x06proto3')
)




_KEYSETREQUEST = _descriptor.Descriptor(
  name='KeySetRequest',
  full_name='tasker_server.KeySetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tasker_server.KeySetRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='tasker_server.KeySetRequest.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=74,
)


_KEYSETRESPONSE = _descriptor.Descriptor(
  name='KeySetResponse',
  full_name='tasker_server.KeySetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_was_set', full_name='tasker_server.KeySetResponse.key_was_set', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_is_new', full_name='tasker_server.KeySetResponse.key_is_new', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=133,
)


_KEYGETREQUEST = _descriptor.Descriptor(
  name='KeyGetRequest',
  full_name='tasker_server.KeyGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tasker_server.KeyGetRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=163,
)


_KEYGETRESPONSE = _descriptor.Descriptor(
  name='KeyGetResponse',
  full_name='tasker_server.KeyGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_exists', full_name='tasker_server.KeyGetResponse.key_exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='tasker_server.KeyGetResponse.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=216,
)


_KEYDELETEREQUEST = _descriptor.Descriptor(
  name='KeyDeleteRequest',
  full_name='tasker_server.KeyDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tasker_server.KeyDeleteRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=249,
)


_KEYDELETERESPONSE = _descriptor.Descriptor(
  name='KeyDeleteResponse',
  full_name='tasker_server.KeyDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='tasker_server.KeyDeleteResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=287,
)


_QUEUEPOPREQUEST = _descriptor.Descriptor(
  name='QueuePopRequest',
  full_name='tasker_server.QueuePopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_name', full_name='tasker_server.QueuePopRequest.queue_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_items', full_name='tasker_server.QueuePopRequest.number_of_items', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=351,
)


_QUEUEPOPRESPONSE = _descriptor.Descriptor(
  name='QueuePopResponse',
  full_name='tasker_server.QueuePopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='tasker_server.QueuePopResponse.items', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=386,
)


_QUEUEPUSHREQUEST = _descriptor.Descriptor(
  name='QueuePushRequest',
  full_name='tasker_server.QueuePushRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_name', full_name='tasker_server.QueuePushRequest.queue_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='tasker_server.QueuePushRequest.priority', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='tasker_server.QueuePushRequest.items', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=459,
)


_QUEUEPUSHRESPONSE = _descriptor.Descriptor(
  name='QueuePushResponse',
  full_name='tasker_server.QueuePushResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='tasker_server.QueuePushResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=497,
)


_QUEUEDELETEREQUEST = _descriptor.Descriptor(
  name='QueueDeleteRequest',
  full_name='tasker_server.QueueDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_name', full_name='tasker_server.QueueDeleteRequest.queue_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=539,
)


_QUEUEDELETERESPONSE = _descriptor.Descriptor(
  name='QueueDeleteResponse',
  full_name='tasker_server.QueueDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='tasker_server.QueueDeleteResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=579,
)


_QUEUELENGTHREQUEST = _descriptor.Descriptor(
  name='QueueLengthRequest',
  full_name='tasker_server.QueueLengthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_name', full_name='tasker_server.QueueLengthRequest.queue_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=621,
)


_QUEUELENGTHRESPONSE = _descriptor.Descriptor(
  name='QueueLengthResponse',
  full_name='tasker_server.QueueLengthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_length', full_name='tasker_server.QueueLengthResponse.queue_length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=666,
)

DESCRIPTOR.message_types_by_name['KeySetRequest'] = _KEYSETREQUEST
DESCRIPTOR.message_types_by_name['KeySetResponse'] = _KEYSETRESPONSE
DESCRIPTOR.message_types_by_name['KeyGetRequest'] = _KEYGETREQUEST
DESCRIPTOR.message_types_by_name['KeyGetResponse'] = _KEYGETRESPONSE
DESCRIPTOR.message_types_by_name['KeyDeleteRequest'] = _KEYDELETEREQUEST
DESCRIPTOR.message_types_by_name['KeyDeleteResponse'] = _KEYDELETERESPONSE
DESCRIPTOR.message_types_by_name['QueuePopRequest'] = _QUEUEPOPREQUEST
DESCRIPTOR.message_types_by_name['QueuePopResponse'] = _QUEUEPOPRESPONSE
DESCRIPTOR.message_types_by_name['QueuePushRequest'] = _QUEUEPUSHREQUEST
DESCRIPTOR.message_types_by_name['QueuePushResponse'] = _QUEUEPUSHRESPONSE
DESCRIPTOR.message_types_by_name['QueueDeleteRequest'] = _QUEUEDELETEREQUEST
DESCRIPTOR.message_types_by_name['QueueDeleteResponse'] = _QUEUEDELETERESPONSE
DESCRIPTOR.message_types_by_name['QueueLengthRequest'] = _QUEUELENGTHREQUEST
DESCRIPTOR.message_types_by_name['QueueLengthResponse'] = _QUEUELENGTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeySetRequest = _reflection.GeneratedProtocolMessageType('KeySetRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYSETREQUEST,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.KeySetRequest)
  ))
_sym_db.RegisterMessage(KeySetRequest)

KeySetResponse = _reflection.GeneratedProtocolMessageType('KeySetResponse', (_message.Message,), dict(
  DESCRIPTOR = _KEYSETRESPONSE,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.KeySetResponse)
  ))
_sym_db.RegisterMessage(KeySetResponse)

KeyGetRequest = _reflection.GeneratedProtocolMessageType('KeyGetRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYGETREQUEST,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.KeyGetRequest)
  ))
_sym_db.RegisterMessage(KeyGetRequest)

KeyGetResponse = _reflection.GeneratedProtocolMessageType('KeyGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _KEYGETRESPONSE,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.KeyGetResponse)
  ))
_sym_db.RegisterMessage(KeyGetResponse)

KeyDeleteRequest = _reflection.GeneratedProtocolMessageType('KeyDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _KEYDELETEREQUEST,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.KeyDeleteRequest)
  ))
_sym_db.RegisterMessage(KeyDeleteRequest)

KeyDeleteResponse = _reflection.GeneratedProtocolMessageType('KeyDeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _KEYDELETERESPONSE,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.KeyDeleteResponse)
  ))
_sym_db.RegisterMessage(KeyDeleteResponse)

QueuePopRequest = _reflection.GeneratedProtocolMessageType('QueuePopRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEPOPREQUEST,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueuePopRequest)
  ))
_sym_db.RegisterMessage(QueuePopRequest)

QueuePopResponse = _reflection.GeneratedProtocolMessageType('QueuePopResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEPOPRESPONSE,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueuePopResponse)
  ))
_sym_db.RegisterMessage(QueuePopResponse)

QueuePushRequest = _reflection.GeneratedProtocolMessageType('QueuePushRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEPUSHREQUEST,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueuePushRequest)
  ))
_sym_db.RegisterMessage(QueuePushRequest)

QueuePushResponse = _reflection.GeneratedProtocolMessageType('QueuePushResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEPUSHRESPONSE,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueuePushResponse)
  ))
_sym_db.RegisterMessage(QueuePushResponse)

QueueDeleteRequest = _reflection.GeneratedProtocolMessageType('QueueDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEDELETEREQUEST,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueueDeleteRequest)
  ))
_sym_db.RegisterMessage(QueueDeleteRequest)

QueueDeleteResponse = _reflection.GeneratedProtocolMessageType('QueueDeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEDELETERESPONSE,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueueDeleteResponse)
  ))
_sym_db.RegisterMessage(QueueDeleteResponse)

QueueLengthRequest = _reflection.GeneratedProtocolMessageType('QueueLengthRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUEUELENGTHREQUEST,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueueLengthRequest)
  ))
_sym_db.RegisterMessage(QueueLengthRequest)

QueueLengthResponse = _reflection.GeneratedProtocolMessageType('QueueLengthResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUEUELENGTHRESPONSE,
  __module__ = 'tasker_pb2'
  # @@protoc_insertion_point(class_scope:tasker_server.QueueLengthResponse)
  ))
_sym_db.RegisterMessage(QueueLengthResponse)



_TASKERSERVER = _descriptor.ServiceDescriptor(
  name='TaskerServer',
  full_name='tasker_server.TaskerServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=669,
  serialized_end=1255,
  methods=[
  _descriptor.MethodDescriptor(
    name='key_set',
    full_name='tasker_server.TaskerServer.key_set',
    index=0,
    containing_service=None,
    input_type=_KEYSETREQUEST,
    output_type=_KEYSETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='key_get',
    full_name='tasker_server.TaskerServer.key_get',
    index=1,
    containing_service=None,
    input_type=_KEYGETREQUEST,
    output_type=_KEYGETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='key_delete',
    full_name='tasker_server.TaskerServer.key_delete',
    index=2,
    containing_service=None,
    input_type=_KEYDELETEREQUEST,
    output_type=_KEYDELETERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queue_pop',
    full_name='tasker_server.TaskerServer.queue_pop',
    index=3,
    containing_service=None,
    input_type=_QUEUEPOPREQUEST,
    output_type=_QUEUEPOPRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queue_push',
    full_name='tasker_server.TaskerServer.queue_push',
    index=4,
    containing_service=None,
    input_type=_QUEUEPUSHREQUEST,
    output_type=_QUEUEPUSHRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queue_delete',
    full_name='tasker_server.TaskerServer.queue_delete',
    index=5,
    containing_service=None,
    input_type=_QUEUEDELETEREQUEST,
    output_type=_QUEUEDELETERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='queue_length',
    full_name='tasker_server.TaskerServer.queue_length',
    index=6,
    containing_service=None,
    input_type=_QUEUELENGTHREQUEST,
    output_type=_QUEUELENGTHRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKERSERVER)

DESCRIPTOR.services_by_name['TaskerServer'] = _TASKERSERVER

# @@protoc_insertion_point(module_scope)
